docs: rework readme
Bearer/bearer pull request #179
Opened 2022-11-30 00:18 UTC by markmichon

## Description

Updates readme based on ongoing notion discussion.

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [x] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

2022-11-30 00:19 UTC, markmichon commented on README.md
> -- GraphQL
We dropped mention of these in the rewrite. Is that okay? @gmontard

2022-11-30 02:13 UTC, markmichon commented
Not sure why this is failing a snapshot test...

2022-11-30 09:51 UTC, gmontard commented on README.md
> -- GraphQL
Right, I've re-added it: https://www.notion.so/bearer/Curio-README-e1b4d88fc8ef43ecb7be826a98b378b5#1f055798fca745a48e83577e0e19bd5d

2022-11-30 10:07 UTC, gmontard requested changes
Added some tiny things to update

2022-11-30 10:07 UTC, gmontard commented on README.md
> +Curio is different as it emphasizes that the most asset we need to protect today is sensitive data, not “systems.” At the same time, it’s built with the knowledge that developers are not security exp
that the most **sensitive** asset

2022-11-30 10:07 UTC, gmontard commented on README.md
> +Curio is a static code analysis tool (SAST) dedicated to data security. It scans your source code to discover sensitive data flows (PHI, PII, PD as well as Data stores, internal and external APIs) an
This part should be removed. After the screenshot, we start directly with "Curio helps..."

2022-11-30 10:07 UTC, gmontard commented on README.md
>  ## Getting started
Should we use emoji with every section? I've seen a few repo do that.

2022-11-30 10:07 UTC, gmontard commented on README.md
> +The number one thing you can do with Curio is protect sensitive data processed by your applications from being exposed by identifying risks. Add Curio to your CI/CD and catch data breach and data lea
by identifying **associated** risks

2022-11-30 10:07 UTC, gmontard commented on README.md
> +Curio also helps your Compliance & Privacy team assess sensitive data flows processed through your applications, allowing them to comply with the growing number of data regulations across the World (
Data **Flow** Report (?)

2022-11-30 10:07 UTC, gmontard commented on README.md
> +| Languages | Data Report | Policy |
Data **Flow** Report ?

2022-11-30 10:07 UTC, gmontard commented on README.md
> +Curio currently fully supports Ruby, while JavaScript/TypeScript support is coming soon. Additional languages listed below are supported only for the Data Report features for now.
Data **Flow** Report

2022-11-30 10:07 UTC, gmontard commented on README.md
> +
In addition, Curio also support those common data structured file formats:
| --- | --- | 
| SQL | ✅ | 
| OpenAPI | ✅ | 
| GraphQL | ✅ | 
| Protobuf | ✅ |

2022-11-30 10:07 UTC, gmontard commented on README.md
> +Out of the box, Curio supports 120+ data types, ranging from Personal Data (PD), to Personal Identifiable Information (PII), Protected Health Information (PHI), and Financial Data. Please refer to th
We'll need to add a link to the doc page

2022-11-30 10:07 UTC, gmontard commented on README.md
> +What if you don't process sensitive data? Well, that's pretty rare these days. Even if you discover no usage after a one-time scan, Curio is a great addition to your CI tooling to ensure sensitive da
sensitive data processing isn't introduced into your codebase **without your knowledge nor risks.**

2022-11-30 16:12 UTC, markmichon commented on README.md
>  ## Getting started
Any suggestions on which emoji for which headings?

2022-11-30 16:17 UTC, markmichon commented on README.md
> +Out of the box, Curio supports 120+ data types, ranging from Personal Data (PD), to Personal Identifiable Information (PII), Protected Health Information (PHI), and Financial Data. Please refer to th
Added. Doc page for data types is in an upcoming PR.

2022-11-30 16:25 UTC, markmichon commented on README.md
> +Curio is different as it emphasizes that the most asset we need to protect today is sensitive data, not “systems.” At the same time, it’s built with the knowledge that developers are not security exp
Updated to important, so it doesn't say sensitive twice on the same line.

2022-12-02 16:46 UTC, gmontard commented on README.md
>  ## Getting started
What about

- Getting started 🚀
- FAQ ❓ 
- Getting in touch 🤚  
- Contributing 🤝
- Code of conduct 🚨
- Security 🛡
- Licence 🎓

2022-12-02 16:54 UTC, markmichon commented on README.md
>  ## Getting started
🙇 Thanks. Will implement 🎉

2022-12-02 17:12 UTC, gmontard approved these changes

2022-12-02 17:12 UTC, gmontard commented on README.md
> +Curio is a static code analysis tool (SAST) that scans your source code to discover security risks and vulnerabilities that put your sensitive data at risk (PHI, PD, PII, Financial data).
I guess we should replace "FInancial" by "Sensitive", as this will be our categorization. We can defer once that part is sette if you want.

2022-12-05 15:42 UTC, merged