chore: better handle typescript
Bearer/bearer pull request #888
Opened 2023-04-11 16:31 UTC by cfabianski

## Description

Typescript is a bit special so we should handle it as such.

## Checklist

- [ ] I've added test coverage that shows my fix or feature works as expected.
- [ ] I've updated or added documentation if required.
- [ ] I've included usage information in the description if CLI behavior was updated or added.
- [ ] PR title follows [Conventional Commits](https://www.conventionalcommits.org/) format

2023-04-11 16:34 UTC, vjerci approved these changes

2023-04-12 07:26 UTC, elsapet commented on pkg/commands/artifact/run.go
> +		output.StdErrLogger().Msg("Loading rules")
Curious why we can't keep `outputhandler` here? Doesn't it mean we are importing `pkg/util/output` twice?

2023-04-12 07:29 UTC, elsapet commented on pkg/commands/artifact/run.go
> -	}
Not sure I understand the changes in this file. This is removing the work I did to cache the bearer-rules. Is it a git / merge issue?

2023-04-12 07:31 UTC, elsapet requested changes
Not sure I'm understanding the pkg/commands/artifact/run.go changes - maybe a manual rebase before merging?

2023-04-12 09:05 UTC, elsapet approved these changes

2023-04-12 09:13 UTC, merged